version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: dtech_db
      POSTGRES_USER: dtech_user
      POSTGRES_PASSWORD: dtech_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
  build: .
  container_name: backend
  restart: always
  command: gunicorn --bind 127.0.0.1:8000 backend.wsgi:application
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  depends_on:
    - db
  environment:
    - NAME=PGDATABASE
    - USER=PGUSER
    - PASSWORD=PGPASSWORD
    - HOST=PGHOST
    - PORT=PGPORT
    - DJANGO_SETTINGS_MODULE=backend.settings
    - DEBUG=False
    - ALLOWED_HOSTS=*
